### ISSUE TITLE
Update GHA to run with recent version of checkout action

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/backup_migrate#107]
That's to prevent "The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2". Not fatal, but can get fixed easily.

Oh, the most recent version is 4 now: https://github.com/actions/checkout

**Comment by indigoxela** [comment]
Unrelated: the Simpletest check failed at first (same error as in #104), but passed on second try (no changes).

I can't dig deeper into that, as I can't get tests passing locally. They never pass. :shrug:

**Comment by argiepiano** [comment]
Thanks @indigoxela. I hadn't noticed you had submitted a PR here - sorry! I already merged a different one that used v3. I'll reconcile the conflicts and will merge this one too, so that it uses v4.
