### ISSUE TITLE
Saved backups delete option should return to saved backups list

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/backup_migrate#111]
When a saved backup is deleted the user is not returned to the list of remaining saved backups and is instead returned to the main backup_migrate page. This is disruptive to the task being done that may include deleting more than one saved backup which has to be done one-by-one. There is no checkbox to select and delete multiple files.

**Comment by argiepiano** [comment]
@izmeez, thank you for posting this issue. I've submitted a PR. Can you please patch the current dev version (not the latest release), and test?

**Comment by argiepiano** [comment]
@cellear, as co-maintainer of Backup & Migrate, would you please test this fix and let me know if you are OK with me merging? Thanks.

**Comment by argiepiano** [comment]
I accidentally did a PR from a new branch in origin instead of my own fork of the module. I'm going to close the linked PR and resubmit a PR from my fork, then remove the branch I accidentally created for this issue.

**Comment by argiepiano** [comment]
New PR submitted.
