### ISSUE TITLE
Some 8.2 deprecation notices persist

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/backup_migrate#116]
Reported in the [Forum](https://forum.backdropcms.org/forum/error-messages-after-making-backup). Apparently `backup_migrate_filter_utils` still contains some dynamic properties.

**Comment by indigoxela** [comment]
Right, also saw some popping up when testing for the d2b module.

**Comment by argiepiano** [comment]
Thanks, @indigoxela. If you find others beyond the ones in `backup_migrate_filter_utils` addressed by the PR here, please let me know. This one on `backup_migrate_filter_utils` is also present in the latest D7 dev version of the module, and has not been reported there yet (the fix they have there for the dynamic properties actually did not include this one - I've just reported it).

**Comment by argiepiano** [comment]
@cellear are you ok with me merging this?
