### ISSUE TITLE
Clean up README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/backup_migrate#13]
Hi @quackers8me, and thank you for porting Backup & Migrate to Backdrop! It looks like the README.md file for this project is not _quite_ properly formatted. 

The only real problem is the first heading "DESCRIPTION:". When properly formatted, this first heading (usually the project name) will be removed by backdropcms.org. Take a look at the modules page to see the problem: https://backdropcms.org/modules?keys=backup

Please refer to our [contributor guidelines](https://github.com/backdrop-ops/contrib) for an [example README.md file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) that you can copy.

**Comment by quackers8me** [comment]
Hi @jenlampton, thank-you for the catch. I've fixed and re-released now.

Cheers,
Jason

**Comment by jenlampton** [comment]
Thank you!
