### ISSUE TITLE
Resolved: Backup of Database and Active config directory fails on WINNT environment

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/backup_migrate#150]
Using the backup_migrate 1.x-1.x code doing a backup on linux environment appears to work fine whether or not compression is on and when it is a combined backup of database and active config directory.

However, on a WINNT environment there are problems. Backup of the database with or without compression works. Whereas, doing a combined backup of Database and Active Config Directory fails on winnt with the following:

```The specified file X:\tmp/bac31B7.tmp.xdev-2024-02-04T10-42-10.db_config.tar could not be moved/copied because no file by that name exists. Please check that you supplied the correct filename.```

Looking at the error there is a combined back slash and forward slash which may be an indication of what may be causing the problem.

Meanwhile, the demo module that also does a backup of the database and a compressed backup of the active config directory works.

I haven't compared the code between the two modules, yet.

**Comment by izmeez** [comment]
On another test a similar error occurs but has more detail:
<pre>
Warning: fopen(X:\tmp/bacDBF1.tmp.xdev-2024-02-04T10-56-00.db_config.tar): failed to open stream: No such file or directory in backup_migrate_filter_compression->_backup_migrate_gzip_encode() (line 114 of \modules\backup_migrate\includes\filters.compression.inc).
    Could not compress backup file. Try backing up without compression.
    Could not complete the backup.
</pre>

**Comment by argiepiano** [comment]
Thanks for reporting, @izmeez! I'm swamped at the moment, but will be going back to this soon.

**Comment by izmeez** [comment]
I have resolved the issue. It was occurring because in the advanced settings the experimental "Use cli commands" was checked. With that unchecked it works.

**Comment by izmeez** [comment]
Closing this issue.
