### ISSUE TITLE
Remove the use of backup_migrate_include() entirely

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/backup_migrate#161]
backup_migrate_include() seems to cause some issues in some instances when it appears in update hooks (see #160). 

In Drupal 7, this function was completely removed. We should do the same. See https://www.drupal.org/project/backup_migrate/issues/3154166

**Comment by izmeez** [comment]
The drupal issue opening explanation may help in understanding this fix:

> With modern PHP there's no need to track which files are loaded, just use [include_once()](https://www.php.net/manual/en/function.include-once.php) when needed and the rest will be taken care of.

**Comment by argiepiano** [comment]
@cellear I would like to merge this PR that has been sitting here for 3 months. I've tested without any issues. Let me know if you can test, and I'll wait a bit for you to do so.

**Comment by cellear** [comment]
Let me see if I can find the time this weekend to make an attempt at that.

**Comment by argiepiano** [comment]
Thanks! Testing should be simple. There is actually no bug, rather a "task" that was ported from D7. So the idea is to install BAM and patch it on a site, then try to create as many types of backups as possible.
