### ISSUE TITLE
Rename to just "backup_migrate"

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/backup_migrate#2]
Awesome @quackers8me! Thanks for moving this over. Could you rename the project to just "backup_migrate" instead of "backup_migrate-backdrop"? Glad to see this transferred correctly, I'd heard from some that moving a repository had caused them trouble.

**Comment by quackers8me** [comment]
Looks like missing that checkbox is causing problems already. I don't have a settings option anymore to be able to change the name. (I checked someone else's contrib module and I do have a setting button there). Could you look and see if you can add the 'Authors' team to this repository?

**Comment by quicksketch** [comment]
Yep, I'll double-check. I may have to move it, which is less than ideal. Hmm. I suppose you could always remove then re-add, but it'll be easier to just move it.

**Comment by quicksketch** [comment]
Just sent a new invite. ;)

**Comment by quicksketch** [comment]
And I renamed the project just for good measure. You may need to delete and re-add your `origin` git remote, or just do a new checkout. Thanks!

**Comment by quackers8me** [comment]
Looks like that didn't work as I couldn't push and the settings button never came back. I've re-pushed it and checked the box properly this time. If you can delete the old backup_migrate repository and then I will rename the backup_migrate_fix one properly. 
Again, sorry, I feel bad for causing more work than necessary.

Jason
