### ISSUE TITLE
Notice: json_decode(): integer overflow detected in ConfigFileStorage->decode()

### ISSUE THREAD

**Issue by dyrer** [backdrop-contrib/backup_migrate#20]
Hello
I have installed backup & migrate to a new server and am getting this error
`Notice: json_decode(): integer overflow detected in ConfigFileStorage->decode() (line 984 of /home/public_html/core/includes/config.inc).`

I have tested the same thing with Kalabox and is working, so I think is something missing from my configuration

**Comment by dyrer** [comment]
Update: I switched to PHP 7 and no error messages

**Comment by quackers8me** [comment]
Hello, I did a quick search on this and it may be due to this issue with the JSON parser:
https://github.com/remicollet/pecl-json-c/issues/13
But PHP 7 has a new JSON extension which may be the reason the 'Notice' no longer appears.

**Comment by quackers8me** [comment]
Hi @quicksketch ,
After thinking about this issue a minute, does Backdrop use the pecl-json-c parser?

**Comment by quackers8me** [comment]
@dyrer This is now fixed in the latest release.
PHP5.6 was more strict in the json_decode library but then they changed json libraries in PHP7.

**Comment by dyrer** [comment]
thank you
