### ISSUE TITLE
Support multisites

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/backup_migrate#21]
I'm using a multisite setup and when trying to backup my 'entire site', it's trying to backup all of my websites (as they're all running off the same copy of Backdrop). Can you please make this module support multisite so that backing up a website only backs up that specific website?

**Comment by quackers8me** [comment]
As this is a new feature request, I will have to defer looking into this due to other commitments.

**Comment by ghost** [comment]
Here's a patch I made for the Drupal version to support multisites. It may help here too...

https://www.drupal.org/project/backup_migrate/issues/2606288#comment-12417122

**Comment by quackers8me** [comment]
@BWPanda I have applied your patch and updated it to backdrop standards (replace drupal instances). I do not have a multisite to test it though. If you can clone branch issue21 and test it would be greatly appreciated.

**Comment by ghost** [comment]
@quackers8me Great! There were a few small issues that I fixed with the attached PR. Other than that, all good!

**Comment by quackers8me** [comment]
merged
