### ISSUE TITLE
Copy/paste error

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/backup_migrate#22]
When creating a new 'File Directory' Source, the help text for the Directory Path field says:

> Enter the path to the directory to save the backups to. Use a relative path to pick a path relative to your Drupal root directory. The web server must be able to write to this path.

This was obviously copied from the help text of the Directory Path field in the 'Server Directory' Destination and needs to be updated appropriately.

**Comment by quackers8me** [comment]
Thanks @BWPanda, this has now been fixed and released.
