### ISSUE TITLE
file_directory_path() has been removed

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/backup_migrate#23]
When trying to restore a full backup of my site, I had an error which Apache's log showed as an issue with the function `file_directory_path()` in `includes/sources.archivesource.inc`. Investigation led me to this:

[file_directory_path() has been removed](https://www.drupal.org/update/modules/6/7#file_directory_path)

So that needs fixing I guess.

**Comment by quackers8me** [comment]
Should be resolved with this patch from the Drupal issue queue. Will fix, test and make release shortly.
https://www.drupal.org/node/2618516

**Comment by quackers8me** [comment]
@BWPanda Hello, can you please test this bug fix on your environment?

**Comment by quackers8me** [comment]
Reopen for testing before creating release.

**Comment by ghost** [comment]
Sorry @quackers8me, because of the issues I was having I am no longer using this module.

**Comment by quackers8me** [comment]
testing complete
