### ISSUE TITLE
Deprecated function: Methods with the same name as their class

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/backup_migrate#24]
I am getting a couple of warnings with PHP 7
Deprecated function: Methods with the same name as their class will not be constructors in a future version of PHP; mime_mail has a deprecated constructor in include_once() (line 107 of ..../httpdocs/backdrop/modules/backup_migrate/includes/crud.inc).
Deprecated function: Methods with the same name as their class will not be constructors in a future version of PHP; backup_file has a deprecated constructor in require_once() (line 496 of .../httpdocs/backdrop/modules/backup_migrate/backup_migrate.module).

**Comment by quackers8me** [comment]
Issue has been filed and fixed in Drupal module dev version.
https://www.drupal.org/node/2623598
Will patch and test with Backdrop version

**Comment by Graham-72** [comment]
Your fix is working with PHP7 here. Thanks.

**Comment by quackers8me** [comment]
Fixed in release 1.0.10
