### ISSUE TITLE
Warning: A non-numeric value encountered.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/backup_migrate#25]
I am getting a warning when viewing saved backups listing.

Warning: A non-numeric value encountered in _backup_migrate_ui_destination_display_file_list() (line 408 of ....../modules/backup_migrate/includes/destinations.inc)

**Comment by Graham-72** [comment]
This issue would seem to be fixed by commit https://github.com/backdrop-contrib/backup_migrate/pull/27/commits/f5048326ec57522685de2a583fceba6480927927 

Apologies, I seem to have muddled things in my attempts to create a PR.

**Comment by quackers8me** [comment]
Fixed in merge commit
