### ISSUE TITLE
Unable to use advanced backup in PHP7.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/backup_migrate#26]
NB This seems to be an issue when using PHP7. It seems OK in PHP5.

When I try the menu item for an advanced backup my site crashes.

....../admin/config/system/backup_migrate/export/advanced

gives me on screen:
Error
The website encountered an unexpected error. Please try again later. 

and I am getting these logged reports:

Warning: Illegal string offset 'data' in _token_token_tree_format_row() (line 637 of ...../core/modules/system/system.theme.inc).
Warning: Illegal string offset 'class' in _token_token_tree_format_row() (line 638 of ...../core/modules/system/system.theme.inc).

**Comment by quackers8me** [comment]
Hi @Graham-72 , I have tested with the latest commits and I cannot get it to fail. 

I'm guessing that it has something to do with your 'site-name' as the advanced page has that field as the default token for the backup filename, and it's related to the error you've posted. Can you post your site-name for testing?
Thank-you.

**Comment by Graham-72** [comment]
Hi @quackers8me thanks for looking at this. I have done a bit more testing and find that it only fails when I have my server set to be using PHP7.1.1. Changing to PHP7.0.15 clears the problem. Interesting!

I have tried on three different sites. The most recent one I have been using had the site name 'oliverhosting.uk' and following your comment I wondered whether the full stop in the name might be causing the problem, but no, changing the name to simply 'oliverhosting' did not make a difference.

**Comment by oadaeh** [comment]
I tried duplicating this on a local install with PHP 7.1.13, and I did not have the problem. Has this been fixed?

**Comment by quackers8me** [comment]
@oadaeh I could not recreate issue so nothing has been done related to php 7.1.
