### ISSUE TITLE
Scheduled backup uses ID and name from other schedule

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/backup_migrate#32]
I had configured a daily database backup schedule on a Backdrop site and added a weekly public files backup schedule later. Both schedules have distinct names: *Daily database backup* vs. *Weekly public files backup*.

When I downloaded the backups I noticed that schedule ID and name in the `.info` files of both backups are the same. ID and name in the `.info` of the files backup are exactly the same as in the database backup:

`schedule_id = "daily_database_backup"`
`schedule_name = "Daily database backup"`

Other details of the `.info` files (`bam_sourceid` and so on) are correct.

**Comment by quackers8me** [comment]
This should be fixed in the current release with issue #43 and a PR by @opi

**Comment by opi** [comment]
hmm, not sure my PR is related to this issue...
