### ISSUE TITLE
Exclusions don't save properly on settings profile pages

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/backup_migrate#33]
When editing a settings profile (`/admin/config/system/backup_migrate/settings/profile/edit`) some iterations of selecting and deselecting tables to be excluded from backups don't work properly in `backup_migrate-1.x-1.0.11`; some selections and deselections aren't preserved upon saving the profile.

Here's what I've observed for the two exclusion fields on my Backdrop 1.8.0 site:

* Exclude the following tables altogether - select list - selecting WORKS
* Exclude the following tables altogether - select list - deselecting WORKS
* Exclude the following tables altogether - checkboxes - selecting WORKS
* Exclude the following tables altogether - checkboxes - deselecting BROKEN
* Exclude the data from the following tables - select list - selecting one not excluded by default WORKS
* Exclude the data from the following tables - select list - deselecting one not excluded by default WORKS
* Exclude the data from the following tables - select list - deselecting one that IS excluded by default (e.g. cache, watchdog) BROKEN
* Exclude the data from the following tables - checkboxes - selecting one not excluded by default WORKS
* Exclude the data from the following tables - checkboxes - deselecting one not excluded by default BROKEN
* Exclude the data from the following tables - checkboxes - deselecting one that IS excluded by default (e.g. cache, watchdog) BROKEN

This seems related to [this Drupal.org issue for backup_migrate in Drupal 7,](https://www.drupal.org/node/2290707) reported fixed in the most recent module release, but the Backdrop behavior differs somewhat from what is described and what we've observed in D7.

**Comment by quackers8me** [comment]
@jackaponte I've had to add two patches from the drupal branch for this issue. Can you please checkout branch 'issue33' and test in your environment.

**Comment by quackers8me** [comment]
merged in patches
