### ISSUE TITLE
Backup config (as separate category)

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/backup_migrate#35]
I'm not sure how much work it would take, but I think it would be great to expand B&M scope to also include config. I had started a site in one place and then was going to duplicate on my localhost, so I set up an empty Backdrop installation, activated B&M, and tried to restore an "entire site" archive. Various things seem to be missing and in a chat on Gitter @quicksketch suggested maybe B&M didn't handle config, which could be the reason.

> I don't think B&M deals with config files. I think you'd need export your full config on the live site, and extra those into your active config directory. Then maybe run B&M? Not sure that would work.
But content would easily go missing on import if the config files for the content types were missing.

> ...seems like something B&M could improve upon. As it didn't need to worry about config in D7, it's probably a shortcoming in its Backdrop version.

**Comment by herbdool** [comment]
I think that's right, no changes were made to work with config files. If your config files are in /files/ you might be in luck if you back up the db and files, otherwise nope.

**Comment by quackers8me** [comment]
@laryn When I ported it I believed I included all the steps to have a proper config setup as I believe this is the strength of Backdrop. 
I checked and BAM does write it's config to: files/config_[yourhash]/active/backup_migrate.settings.json
and when you run the export sync 
`see` admin/config/development/configuration/sync
and check the archive the BAM json is in there.
Maybe a portion of the setting is not written out correct to the config file? 
Any idea on a way to test this?

**Comment by laryn** [comment]
@quackers8me Just to make sure we're talking about the same thing, I'm not referring to BAM saving its own settings in a config file, but including all config files in the "entire site" backup archive to download and restore on another site.

**Comment by herbdool** [comment]
@quackers8me from what I understand that only works if the config files are in the files directory. We can't assume that. The config directory is defined in settings.php

I think a new source should be written to capture config in all cases.

**Comment by quackers8me** [comment]
Ok, I understand now. Should the 'Sources' option be changed from DB to 'DB and Configs dir', and the Entire site would also include configs dir?

**Comment by laryn** [comment]
That sounds reasonable to me.

**Comment by Graham-72** [comment]
This will be very useful. 👍

**Comment by jenlampton** [comment]
Plus one for this whole conversation!  Ideally I'd like to see:
* `Configuration directory` to appear in the "Backup Source" options list by itself
* `Entire site (code, files, & db)` changed to `Entire site (code, files, db & config)`

**Comment by wilburec** [comment]
I'm interested to work on this issue.  

Can we expand this ticket to include Config as a category:
- Default Database
- Public Files Directory
- Active Configuration
- Entire Site (code, files, configuration, DB)

If that is the case, we should rename this issue to reflect that. 

This would also make this issue a duplicate - #59

**Comment by herbdool** [comment]
I agree that the other one is a duplicate. I've closed it.

**Comment by herbdool** [comment]
@wilburec I'll happily review your work if you like.

**Comment by stpaultim** [comment]
Yes, I'd like to see this too.

**Comment by quackers8me** [comment]
Merged in PR #71
