### ISSUE TITLE
[UX] Operations should be converted to drop-buttons

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/backup_migrate#39]
The "Operations" column on the right hand side of the schedules page contains three links, edit, delete, and export, and the wrapping of text in that column makes the links hard to scan. Can we convert these into a drop-button instead? That would be consistent with the rest of Backdrop's admin UI.
<img width="1190" alt="screen shot 2018-03-30 at 3 09 03 pm" src="https://user-images.githubusercontent.com/397895/38155503-ea4c2ac2-342c-11e8-9d3b-5ec8ba128fcc.png">

The same is true for the settings page:
<img width="380" alt="screen shot 2018-03-30 at 3 16 11 pm" src="https://user-images.githubusercontent.com/397895/38155572-538faf2c-342d-11e8-90bf-1742a4347d84.png">

**Comment by quackers8me** [comment]
I took a look and I think this task is beyond my kin. 
It looks like the Operations links are generated dynamically from BAM's crud.inc but I'm not clear on how you could wrap that in the drop-button UI? I could not find how this UI is called in the admin. The only reference in the API is:
https://api.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_dropbutton_wrapper/1
but that function is never called in core modules.

**Comment by jenlampton** [comment]
> but that function is never called in core modules.

Yeah, it's a little crazy for sure. A theme wrapper is attached to a render array rather than being called directly, so it can be hard to find examples. I'll see if I can file a PR for it.

**Comment by argiepiano** [comment]
@jenlampton, here's a PR: #90. Can you please test?

**Comment by argiepiano** [comment]
Reopening while people test this.

**Comment by argiepiano** [comment]
Closing now that this PR is included in version 1-x.1.0.23
