### ISSUE TITLE
NodeSquirrel settings fatal error

### ISSUE THREAD

**Issue by sirkitree** [backdrop-contrib/backup_migrate#4]
This path: /admin/config/system/backup_migrate/nodesquirrel
Gives a fatal error: Fatal error: Class 'backup_migrate_destination' not found in /Users/sirkitree/repos/beta.vrsites.com/docroot/modules/contrib/backup_migrate/includes/destinations.nodesquirrel.inc on line 351

**Comment by quackers8me** [comment]
This is now fixed with the generous help of @ronan
