### ISSUE TITLE
"Edit Schedule" still links to Drupal pages/projects

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/backup_migrate#40]
The "Edit Schedule" page directs people to Drupal pages and projects:

- Cron links to Drupal documentation (but could be linked to the site's cron settings page). [Related](https://github.com/backdrop/backdrop-issues/issues/3044).
- Elysia Cron and Drush both link to the Drupal projects but should link to the Backdrop versions instead.

PR coming.

**Comment by quackers8me** [comment]
Thanks @laryn
