### ISSUE TITLE
Can't enable module for the second time.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/backup_migrate#42]
When I enable this module, then disable, then enable again, I get an error, and the caches are not cleared after the module enables.

In my dblog, I see this:
```
DatabaseSchemaObjectExistsException: Table backup_migrate_profiles already exists. in DatabaseSchema->createTable() (line 662 of backdrop/includes/database/schema.inc).
```

**Comment by quackers8me** [comment]
Hi @jenlampton , I couldn't reproduce this error with Backdrop 1.11.2 and the current backup_migrate. I will leave this bug open in case other users experience this issue.

**Comment by quackers8me** [comment]
Closed since no others have reported this bug
