### ISSUE TITLE
backup_migrate_schedule_last_run variable should be store as state, not config

### ISSUE THREAD

**Issue by opi** [backdrop-contrib/backup_migrate#43]
The variable `backup_migrate_schedule_last_run_ID` change upon each schedule run. It results as a diff in config managment, even if real config has no change.

I recommend saving this variable as a state (using [state_set](https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_set/1) & [state_get](https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_get/1)).

Before crafting a PR, I'd like some principle agreement.

**Comment by herbdool** [comment]
Absolutely. I agree.

**Comment by opi** [comment]
Created PR #44
