### ISSUE TITLE
Incorrect backup_migrate_smart_keep_weekly value

### ISSUE THREAD

**Issue by opi** [backdrop-contrib/backup_migrate#46]
From https://github.com/backdrop-contrib/backup_migrate/blob/1ab61612b43d0a4a5b92e43d1a9a4657f46b7876/config/backup_migrate.settings.json#L30

`"backup_migrate_smart_keep_weekly": 2147483647,`

I guess this should be something like 4... but it seems to be intentional https://github.com/backdrop-contrib/backup_migrate/commit/1ab61612b43d0a4a5b92e43d1a9a4657f46b7876#diff-65910faaf5871d4388da6c06cd01d8a1

can you explain this value ?

**Comment by Radcliffe** [comment]
This value is 2^31 - 1, which is the largest 32-bit signed integer. I suppose it means that all weekly backups should be kept. The previous value was 2^63 - 1, the largest 64-bit signed integer.

**Comment by quackers8me** [comment]
Yes, the default is to keep all weekly backups. The original Drupal module
used this as a setting:

define('BACKUP_MIGRATE_SMART_KEEP_WEEKLY', PHP_INT_MAX);

But that constant couldn't be added to the BD settings.json so I
hardcoded the largest 32 bit integer.

**Comment by opi** [comment]
is it really relevant to keep every weekly backup ?

- hourly are kept for a day
- daily are kept for a week
- My guess is that weekly should be kept for a month...

( Backdrop is a grown boy now, and could emancipate from Drupal oddities :p )

**Comment by Wylbur** [comment]
I just ran across this error.  By selecting smart backups, it seems you will eventually run out of space for backups.  

Perhaps a better scheme would be 
- hourlys for a day - 24
- dailys for a week - 7
- weeklys for 3 months - 12
- monthly for 3 years - 36

That would make a finite set of backups.  

The current value of weeks is pretty silly.
