### ISSUE TITLE
[UX] Unable to configure module - settings page/form missing (Notice: Use of undefined constant BACKUP_MIGRATE_MENU_PATH)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/backup_migrate#47]
As of the latest release (1.x-1.0.14) the menu path `admin/config/system/backup_migrate` only loads the system page `admin/config/system` and the settings form can't be reached.

**Comment by jenlampton** [comment]
The same is true for 1.x-1.0.13

**Comment by jenlampton** [comment]
The same is true for 1.x-1.0.12

**Comment by jenlampton** [comment]
The same is true for 1.x-1.0.11

**Comment by jenlampton** [comment]
The same goes for 1.x-1.0.10.

**Comment by jenlampton** [comment]
I've rolled all the way back to version 1.x-1.0.1 and still can't get anything to appear at `admin/config/system/backup_migrate`. I've also noticed that the "Configure" link on the modules page renders as `admin/config/system` which confirms the menu router issue. Backdrop has no idea there's a page located at `admin/config/system/backup_migrate`.

This is strange to me, as I know I have several sites running older versions of B&M. I'll ch check which versions those were.

**Comment by jenlampton** [comment]
I've confirmed that I have one site running version 1.x-1.0.13, and for that site the form loads correctly at admin/config/system/backup_migrate. 

Since it works fine there, I went back and completey uninstalled Backup & Migrate from this problem site, and installed 1.x-1.0.14 from scratch, and now everything seems to be working just fine.

This site was upgraded from Drupal 6 (and then Drupal 7) so I wonder if there's an issue with using a constant `BACKUP_MIGRATE_MENU_PATH` for the menu path on upgraded sites.

Perhaps the upgrade path needs to forcibly set (or reset?) that value?

**Comment by jenlampton** [comment]
Ah yep. My log is flooded with PHP notices

```
Notice: Use of undefined constant BACKUP_MIGRATE_MENU_PATH - assumed 'BACKUP_MIGRATE_MENU_PATH' in backup_migrate_item->get_settings_path() (line 728 of backdrop/modules/contrib/backup_migrate/includes/crud.inc).
```

**Comment by herbdool** [comment]
`BACKUP_MIGRATE_MENU_PATH` is defined in backup_migrate.module so it should be defined so long as the module is enabled I think. I can't replicate the upgrade from D6/D7 but on a fresh install I don't see the error.

**Comment by jenlampton** [comment]
Well, the work-around was trivial Uninstall in D6/D7 and re-install in Backdrop. It was easy enough to re-configure. I'll test this again on my next upgraded site, but for now I cannot reproduce it either.
