### ISSUE TITLE
Add an upgrade path, remove old update hooks

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/backup_migrate#5]
Hi @quackers8me! Nice job on porting this module. It looks like we still have all the update functions from the Drupal 7 module in the .install file, including some updates in the 2xxx numbering. Because Backdrop update numbers start over at 1000, this can cause some screwy behavior.

To provide an upgrade path, all existing update hooks should be removed from the .install file, add a hook_update_1000() to upgrade settings to config, and add hook_update_last_removed().

**Comment by Graham-72** [comment]
This is very helpful guidance on what should be in the .install file for Backdrop. Is it documented somewhere else for future reference?

**Comment by quackers8me** [comment]
Thanks @quicksketch, I didn't realize the old updates needed to be removed. 
Completed now.

**Comment by herbdool** [comment]
It is documented on the module conversion page https://api.backdropcms.org/converting-modules-from-drupal

**Comment by Graham-72** [comment]
Thanks for that reminder and link.
