### ISSUE TITLE
Nodesquirrel is no more (sad face)

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/backup_migrate#50]
I guess we can remove that functionality from the module. Hopefully someone comes up with a good alternative.

**Comment by quackers8me** [comment]
Yes, it will have to be removed. Here are the relevant dates:
"When Will NodeSquirrel Go Away?
NodeSquirrel will stop accepting backups after September 30, 2019.

How Long Will Backups be Stored?
Users will be able to download backups through November 1, 2019."

Source: https://pantheon.io/nodesquirrel-service-end-life

**Comment by quackers8me** [comment]
Will need to integrate this D7 patch
https://www.drupal.org/project/backup_migrate/issues/3051821

**Comment by herbdool** [comment]
@quackers8me I've created a PR based on the d.o issue https://github.com/backdrop-contrib/backup_migrate/pull/53 . The d.o hasn't been merged yet but looks like it works.

**Comment by jenlampton** [comment]
Update 1007 won't run for me because the function `backup_migrate_include()` is not defined. 
edit: I've added a comment on the PR.

**Comment by quackers8me** [comment]
close for merge with #53
