### ISSUE TITLE
Fix file encryption option

### ISSUE THREAD

**Issue by oadaeh** [backdrop-contrib/backup_migrate#55]
On the configuration pages, on the Backup tab, on the Advanced Backup sub-tab, in the Backup File field set, there is a File Encryption setting that references the Drupal AES encryption module. That module is:
- A Drupal module that has not been ported to Backdrop
- Unsupported due to a security issue the maintainer didn’t fix

The first thing that probably should be done is to remove that option or re-word it so it is not pointing to an unsupported Drupal module.

The next thing that should be done is to port the [Encrypt](https://www.drupal.org/project/encrypt) module and use that one, since support for it was added to the 7.x-3.x branch of the D7 module in March of 2019: https://www.drupal.org/project/backup_migrate/issues/2135813

**Comment by quackers8me** [comment]
I have just removed the text so that any sites that may already be using this are unaffected.
