### ISSUE TITLE
Remove NodeSquirrel from README

### ISSUE THREAD

**Issue by mbomb007** [backdrop-contrib/backup_migrate#57]
NodeSquirrel stopped accepting backups after September 30, 2019.

https://pantheon.io/nodesquirrel-service-end-life

https://github.com/backdrop-contrib/backup_migrate/issues/50

**Comment by laryn** [comment]
Thanks! Looks like the functionality was removed in https://github.com/backdrop-contrib/backup_migrate/pull/53 but the README wasn't updated. Would you file a PR to remove it from the README?

**Comment by mbomb007** [comment]
Pull Request: https://github.com/backdrop-contrib/backup_migrate/pull/58
