### ISSUE TITLE
Backup Config Files

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/backup_migrate#59]
Feature request. 

When updating a site, I believe that it probably makes sense to backup the database, the files, and the config directory. I can backup the database and files (and code) with Backup and Migrate, but I must go to the config export to backup the config directory. 

I think it would be really great if Backup and Migrate were able to create a backup of config files. It would be nice to be able to schedule config backups. 

If users always commit their code to their repo, they are in good shape. But, since config changes often happen on the server and do not get committed immediately, the config directory is vulnerable to mishaps. Also, many of our users might not keep their config in a git repo. Many of them might not use git at all.

**Comment by laryn** [comment]
May be a duplicate of https://github.com/backdrop-contrib/backup_migrate/issues/35
