### ISSUE TITLE
Use of DRUPAL_ROOT

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/backup_migrate#6]
At line 506 in backup_migrate.module should it not be BACKDROP_ROOT ?

**Comment by quackers8me** [comment]
Hi @Graham-72, Thanks for catching that and I found some other Drupal references and hooks that could be replaced. Also merged in changes from recent Drupal module update.

**Comment by Graham-72** [comment]
:+1:  Thanks for porting this module. It would be good now to have it as a formal release so that it is recognised by update.

**Comment by quackers8me** [comment]
I wasn't aware of that and have now created a release. Thanks for pointing that out.

**Comment by Graham-72** [comment]
And the system needs a line added to the .info file giving the type of the project i.e.
type = module

I got caught out by this one when I first created a release.

**Comment by quackers8me** [comment]
Thanks again, also caught that my merge wasn't complete.

**Comment by Graham-72** [comment]
I have found a couple more DRUPAL_ROOTs in includes/destinations.file.inc

**Comment by quackers8me** [comment]
Thank-you. Cleaned up now.
