### ISSUE TITLE
Possible Problem with Backup and Migrate Restore DB

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/backup_migrate#64]
Just creating this ticket based upon this issue reported in the forum. I assume that this user also updated core to 1.19.0.

> I updated the backup_migrate module and it was able to successfully create a backup.  However when I try to restore the backup. I get the following error:

> Call to unidentified method DatabaseConnection_mysql::prepare()

> I am testing on some local development sites. The backup seems correct when I manually restore the database.

https://forum.backdropcms.org/comment/2867#comment-2867

I have not recreated or confirmed this issue. Has anyone else had this problem?

**Comment by quackers8me** [comment]
I can confirm the issue and found that it's due to removing the 'exends PDO' from the DatabaseConnection class to accommodate PHP8. I am looking for a solution and have reached out to the Drupal module maintainer.

**Comment by stpaultim** [comment]
@quackers8me - Thanks for the follow-up. 

The user who reported this problem added the following information to the forum discussion. 

> I was using a fresh install of backdrop 1.19.0.  No other modules; just backup_migrate.

**Comment by quackers8me** [comment]
In discussion with the D7 maintainer, the fix may require a change to backdrop core.

**Comment by quicksketch** [comment]
The core issue for tracking this is https://github.com/backdrop/backdrop-issues/issues/5094. Though we don't have any suggestion yet as to what the right fix would be on the core side either.

**Comment by quackers8me** [comment]
@quicksketch I wasn't sure if it should go there so I created a new one. I will update that issue instead.

**Comment by stpaultim** [comment]
I experienced this problem on one of my own sites yesterday.
