### ISSUE TITLE
Edit Schedule form page does not include breadcrumb, page title, and module tabs

### ISSUE THREAD

**Issue by wilburec** [backdrop-contrib/backup_migrate#66]
When editing an existing schedule item,  the form page does not display any of the navigation items.  (See screenshots)

If you want to stop editing, and just return to other module options, they are not available from this form.  

Solution - Present this form with the module navigation items.
![Screenshot from 2021-06-01 15-11-23](https://user-images.githubusercontent.com/33846440/120384732-2728fc80-c2ec-11eb-9394-e96a4be55ddc.png)
![Screenshot from 2021-06-01 15-09-51](https://user-images.githubusercontent.com/33846440/120384734-2728fc80-c2ec-11eb-9d1f-62b0c524e6d6.png)

**Comment by argiepiano** [comment]
PR #86 submitted. @wilburec, are you able to test this?

**Comment by argiepiano** [comment]
Reopening while people test this.

**Comment by argiepiano** [comment]
Closing now that this PR is included in version 1-x.1.0.23
