### ISSUE TITLE
Improve Create Destination Form Descriptions and Labels

### ISSUE THREAD

**Issue by larsdesigns** [backdrop-contrib/backup_migrate#69]
The language for the form fields is a little confusing. 

1. - [x] Improve the field descriptions and labels.

**Comment by larsdesigns** [comment]
Created pull request: https://github.com/backdrop-contrib/backup_migrate/pull/70

**Comment by quackers8me** [comment]
@larsdesigns Thank-you for all these updates! I noticed a couple errors in my testing and have fixed. Please pull again from 1.x-1.x and test. If it works for you I'll issue a release.

**Comment by larsdesigns** [comment]
@quackers8me, Thanks, it looks good to me.
