### ISSUE TITLE
Database update 1006 is failing during website import from Drupal 7

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/backup_migrate#72]
I'm importing a Drupal 7 website to backdrop for the first time.  When I am running the update, it fails with the following error message:
`An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://sapsbd.docksal/core/update.php?op=selection&token=AgdxKy0g68L-6kIg_AZ9oCY93iLny-T_B9UdZArAmCQ&id=707&op=do_nojs&op=do StatusText: Service unavailable (with message) ResponseText: Error: Call to undefined function backup_migrate_include() in backup_migrate_update_1006() (line 494 of /var/www/modules/backup_migrate/backup_migrate.install).`

I'll try this again on a few more migrations, but just wanted to document this here to see if anyone else has run into this.

**Comment by quackers8me** [comment]
I think you've found a bug in the install file where it's not loading the module into memory first. I believe that 1006 function should include:
`  module_load_include('module', 'backup_migrate', 'backup_migrate'); ` 
before trying to "Get schedule"
I will do further testing and issue a new release if this is the case.

**Comment by Wylbur** [comment]
@quackers8me 

### Testing
Adding the code line at line 494 of backup_migrate.install resolved the install messages perfectly!  

I have further error messages now, and will start additional issues for those items.  

Thanks for your quick response!
