### ISSUE TITLE
Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1678 of /Applications/MAMP/htdocs/rc-1b/core/modules/system/system.tar.inc).

### ISSUE THREAD

**Issue by abetomas** [backdrop-contrib/backup_migrate#75]
I got this message when backing up entire site:
`Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1678 of /Applications/MAMP/htdocs/rc-1b/core/modules/system/system.tar.inc).`
However, (a) the backup files were actually generated in the Manual Directory, (b) the messages were not flagged as errors in the log messages report! ???

<img width="1195" alt="Screen Shot 2022-07-22 at 12 17 56 AM" src="https://user-images.githubusercontent.com/9346415/180362353-42bf8f0e-b975-43a1-8e64-8bc4c5bf3b79.png">

**Comment by quackers8me** [comment]
@abetomas Which version of PHP are you running? I found the following post on the Drupal issue queue: https://www.drupal.org/project/backup_migrate/issues/3265002

**Comment by abetomas** [comment]
> @abetomas Which version of PHP are you running? I found the following post on the Drupal issue queue: https://www.drupal.org/project/backup_migrate/issues/3265002

Thanks for your response.
The MAMP PHP version was 5.6.40, I changed the version to PHP version 7.4.21 and the same messages were displayed.  However, the backup files were also created.

<img width="798" alt="Screen Shot 2022-08-14 at 11 41 39 PM" src="https://user-images.githubusercontent.com/9346415/184573490-ed7355d7-4a2f-4c8f-ab5b-afdb09cb1805.png">

**Comment by indigoxela** [comment]
Can you give us a little more info about your whole local dev setup? (Obviously this is a local install.)

**Comment by abetomas** [comment]
> Can you give us a little more info about your whole local dev setup? (Obviously this is a local install.)

Thank you for your response.  My local dev setup:
- MacBook Pro M1-chip, Monterey MacOs 12.5, 8gb memory, 512gb SSD drive
- MAMP (free version)
- Please see attached pdf for backdrop status
- it's a very small test setup for a community site, compressed tarball of test site is only 20mb 
[Status-report.pdf](https://github.com/backdrop-contrib/backup_migrate/files/9347528/Status-report.pdf)

Please let me know if you need more info.  Thanks again.

**Comment by argiepiano** [comment]
This seems like an oversight when writing the method `_writeLongHeader()`. If you check `_writeHeader()` and `_writeHeaderBlock()`, both define `$v_version` and `$v_magic`. However, `_writeLongHeader()` doesn't  - thus the notice. The fix is pretty simple - just define the variables.

Oh, and this is a core bug, BTW!

**Comment by argiepiano** [comment]
Core PR submitted https://github.com/backdrop/backdrop/pull/4441

This was previously reported here https://github.com/backdrop/backdrop-issues/issues/3492
