### ISSUE TITLE
Include Port Number Option for Database Connections

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/backup_migrate#78]
When connecting Backup/Migrate to Pantheon sites, they use non-standard port numbers (usually a 5-digit port, e.g. 63478, that is random per site). It would be great to have this port number exposed as an option for a backup destination.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop-contrib/backup_migrate/pull/79. Seemingly this is trivial because Backup and Migrate saves and utilizes port numbers if available (such as from reading settings.php port numbers) but there's just no field for entering a value on the destinations form.

**Comment by quackers8me** [comment]
@larsdesigns is co-maintainer and should be able to create a release.

**Comment by irinaz** [comment]
Pantheon is changing port numbers once in a while for existing sites, so missing option to add port number is a blocker for this module.
