### ISSUE TITLE
PHP 8: Error messages: RESTORE / SAVED BACKUPS when using FTP Destination

### ISSUE THREAD

**Issue by tikita** [backdrop-contrib/backup_migrate#80]
Hello,

I know Backup & Migrate from Drupal 7 but have a problem here on a freshly installed Backdrop:

It works: create backups to the directories

```
Manual Backups Directory	private://backup_migrate/manual
Scheduled Backups Directory 	private://backup_migrate/scheduled
```
But when I click on the tab **Restore** this error appears:

```
Restoring will delete some or all of your data and cannot be undone.
Always test your backups on a non-production server!
ftp_systype(): Argument #1 ($ftp) must be of type FTP\Connection, null given 
```

And when I click on the tab **Saved Backups** this error appears:

`ftp_systype(): Argument #1 ($ftp) must be of type FTP\Connection, null given `

--

_Backup and Migrate 1.x-1.0.21
Backdrop CMS 1.23.0
PHP 8.1.7
Firefox 107_

Many greetings, Tikita

**Comment by olafgrabienski** [comment]
I'm using Backup and Migrate as well and don't see the error. Searching Drupal issue queue I found however a similar issue:

https://www.drupal.org/project/backup_migrate/issues/3305432

From what I read there, it seems to be an issue with PHP 8.

**Comment by olafgrabienski** [comment]
And one question: Is Backup and Migrate somehow configured to use a FTP connection?

**Comment by tikita** [comment]
Yes, I had set up another backup destination to an FTP server. If I remove this, then the error message no longer appears. Thanks for your hint!

But it's also a PHP problem: the [PHP manual](https://www.php.net/manual/en/function.ftp-systype.php) writes about **ftp_systype** that with version 8.1 "the ftp parameter expects an FTP\Connection instance now; previously, a resource was expected". 

It would be great if _Backup and Migrate_ would also work with PHP 8.1.

**Comment by argiepiano** [comment]
PR #85  provided and ready for testing/review.

Please test this with the current dev branch (or by patching the most recent release), which includes another FTP fix.

**Comment by argiepiano** [comment]
@tikita are you able to test this fix?

**Comment by argiepiano** [comment]
Reopening while people test this.

**Comment by tikita** [comment]
Hello, when I set up a backup destination to an FTP server, and when when I click on the tab _Saved Backups_ then the error message still appears:

`ftp_systype(): Argument #1 ($ftp) must be of type FTP\Connection, null given`

Backup and Migrate 1.x-1.0.22
Backdrop CMS 1.25.1
PHP 8.1.15
Firefox 114.0.1

Tikita

**Comment by argiepiano** [comment]
@tikita thanks. Are you using the dev version of the module to test?

**Comment by tikita** [comment]
I look on https://backdropcms.org/node/182/releases-table and do not see a dev version.

**Comment by argiepiano** [comment]
The dev version is the 1.x-1.x branch. You can download it here:
[Download ZIP](https://github.com/backdrop-contrib/backup_migrate/archive/refs/heads/1.x-1.x.zip)

Can you please try this with that version and report back? Thanks.

**Comment by tikita** [comment]
I have uninstalled Backup and Migrate 1.x-1.0.22.

Then I installed backup_migrate-1.x-1.x.

The error message when I click on _Saved Backups_ (see above) does not appear now.

But I get the message

`FTP Error: Couldn't change into the var/www/vhosts/hosting******.*****.netcup.net directory`

and this surprises me, because I know exactly the data of the external server and I always access it (e.g. with Filezilla).

![backup-migrate-ftp-zugang](https://github.com/backdrop-contrib/backup_migrate/assets/6100237/d82520f7-9d9b-4225-b59f-5e4ae4890880)

PS: I have also asked the provider (Netcup) for support, let's see what comes from there.

**Comment by argiepiano** [comment]
Thanks for testing! In path be sure to put the path where the files are from the point of view of the ftp logged in account, NOT the absolute path of the server. So, for example, if your files are in a folder `my-files`  **from the point of view of the logged in FTP user**, the enter `my-files`. If the files are in the root  **from the point of view of the logged in FTP user**, then enter `./`

**Comment by tikita** [comment]
Thanks for pointing out that only a folder needs to be specified, but unfortunately no:

`myfolder` or
`/myfolder` or
`myfolder/`

or simply specify the base directory with

`./`

will always lead to the error message

`FTP Error: Couldn't change into the myfolder directory`
`FTP Error: Couldn't write to ./mysite-2023-07-01T22-07-02.sitearchive.tar.gz when trying to save file on the ftp server.`
`Could not run backup because the file could not be saved to the destination.`

**Comment by argiepiano** [comment]
Although this PR is  included in 1.x-1.0.23, I'll leave this open to do some more testing. In my tests, this works, but I'll need to take a closer look at @tikita's comments.

**Comment by tikita** [comment]
Updated Backdrop CMS to version 1.26.0 today.

Regarding the unchanged installed backup_migrate-1.x-1.x. there was no new reaction except the already mentioned messages.

But I found another protocol note:

_Warning: ftp_nlist(): Connection timed out in backdrop_ftp_file_list() (Zeile 306 von /hp/cw/ab/cc/www/myfolder/modules/backup_migrate-1.x-1.x/includes/destinations.ftp.inc)._

**Comment by argiepiano** [comment]
@tikita, FTP is working for me in the latest version of Backup and Migrate (version 1-x.1.0.23). The configuration is a bit tricky with FTP in general. I'm pasting screenshots. Hopefully that will help you configure the destination correctly. If not, this may be a problem with your host. 

First I created my FTP account. I use cPanel in my host to do this. IMPORTANT: notice that, while cPanel added a Directory to my account (that is, tenutoweb.com/myftp) that path is **invisible** to my ftp account once I'm logged in. See the Backdrop configuration below for this.
 
<img width="772" alt="Screen Shot 2023-09-17 at 8 09 31 AM" src="https://github.com/backdrop-contrib/backup_migrate/assets/9938978/a9f82e5b-bb6f-49e2-aed8-7b9688f92f0a">
 
Once I have that, I configure Backup and Migrate. I added a new FTP destination:

<img width="758" alt="Screen Shot 2023-09-17 at 8 40 00 AM" src="https://github.com/backdrop-contrib/backup_migrate/assets/9938978/732250f5-5b7c-4359-83bd-3e9b86991c2c">

A very important point: I put `/` in the path, NOT the full path. This is the **relative** path for my ftp user once it's logged in. IF you want to put files within a sub-folder, then you **must** create that sub-folder by logging in using an FTP client program, and creating a subfolder. 

I then try creating a backup. Just to make sure that the backup worked, I go to Settings and click "List Files"

<img width="1179" alt="Screen Shot 2023-09-17 at 8 46 35 AM" src="https://github.com/backdrop-contrib/backup_migrate/assets/9938978/3744ce32-c914-4934-8cde-f76d826373a6">

And I can see the file of the last (and only) backup in my account:
<img width="1238" alt="Screen Shot 2023-09-17 at 8 46 52 AM" src="https://github.com/backdrop-contrib/backup_migrate/assets/9938978/47cc27cb-e9e9-4cc1-b4d1-9e7002373a0c">


So, as you see, this is working fine. Your issues are either configuration problems, or hosting problems.

**Comment by tikita** [comment]
Oh how nice, now it finally works for me: uninstalled backup_migrate-1.x-1.x and installed version 1-x.1.0.23.

The module still can't access the top level with the path "/" (it's different for each provider) but with e.g. "/httpdocs" or the subdirectory "/httpdocs/myfolder" _Backup and Migrate_ works fine now in the exchange via FTP.

Thank you Alejandro for your work and for staying so persistent on the problem!

Many greetings from Tikita

PS: With my provider (not all of them) you have to use passive mode for FTP, so check the box "Use PASV transfers" (just below the "Password" field).

**Comment by argiepiano** [comment]
Great to know, @tikita . Thanks for your patience. I'll add your notes to the readme

**Comment by argiepiano** [comment]
I've added these directions and your comment to the [wiki](https://github.com/backdrop-contrib/backup_migrate/wiki) of the module. Thanks.
