### ISSUE TITLE
Cross port all "Advanced settings" functionality and update the module to current D7 state, add tests

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/backup_migrate#91]
D7's current version includes a number of settings available under "Advanced settings". Most of these settings don't exit in Backdrop's current version:
- `backup_migrate_memory_limit`
- `backup_migrate_backup_max_time` (exists in B, but doesn't allow to modify through UI)
- `backup_migrate_verbose`
- `backup_migrate_disable_cron`
- `backup_migrate_data_rows_per_query`
- `backup_migrate_data_rows_per_line` (exists in B, but can't be changed through the UI)
- `backup_migrate_data_bytes_per_line` (exists in B, but can't be changed through the UI)
- `backup_migrate_max_email_size` (same)
- `backup_migrate_cleanup_temp_files` (same)
- `backup_migrate_cleanup_time` (same)
- `backup_migrate_schedule_buffer` (same)

This is a blocker for #87

**Comment by argiepiano** [comment]
This issue was expanded to incorporate most of the D7 changes that happened after the initial port. This included the advanced settings functionality, plus a few other new or changed features.

Additionally, there is some general cleanup of commented out code, and leftovers "Drupal" in `backup_migrate.js`.

**Comment by argiepiano** [comment]
Additionally, this takes care of #87. Closing that one.

**Comment by argiepiano** [comment]
PR #92 ready for testing.

**Comment by argiepiano** [comment]
I've added all relevant automated tests as well.

**Comment by argiepiano** [comment]
Reopening while people test this.

**Comment by indigoxela** [comment]
@argiepiano thank you so much for all your work! :pray:

After some testing, I found something odd: when trying to restore the active **config**, I get the screen for a database restore, which pretty misleading.

If I hit the restore button, I get:

```
    Unable to restore from file /tmp/backup_migrate_3lbxCr.tar because a tar file can't be restored to this database.
    Could not perform the restore.
```
No, of course that won't work, I'm trying to restore config, not the database. :wink: (I'm aware, that oddity existed before.)

**Comment by indigoxela** [comment]
OK, I'm just playing "user from hell", but realized, that BM lets me restore the config to the files directory – definitely where they do not belong. Should I open a new issue for that?

As for the other (newly added) advanced settings: I didn't test in all detail, but the functionality seems to work just fine. :+1:

**Comment by argiepiano** [comment]
Thanks @indigoxela. I started maintaining this module very recently and have never tried the config backup and restore. If you could open a separate issue that'd be great. 

>  that BM lets me restore the config to the files directory – definitely where they do not belong

Can you clarify what you mean by this? Maybe in the new issue? Thanks!

**Comment by argiepiano** [comment]
Closing now that this PR is included in version 1-x.1.0.23
