### ISSUE TITLE
Deprecated function: preg_match(): Passing null to parameter #2 ($subject) of type string

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/backup_migrate#94]
When doing a manual backup with php 8.1.17 and backup_migrate 1.x-1.0.23 the following error is displayed:
`Deprecated function: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in _backup_migrate_to_bytes() (line 1912 of ...backup_migrate.module).`

**Comment by drupix** [comment]
Line 1396 of `backup_migrate.module` must be `$backup_migrate_memory_limit = config_get('backup_migrate.settings', 'backup_migrate_memory_limit');`

Note the `backup_migrate.settings` in the first parameter of config_get

**Comment by argiepiano** [comment]
Thank you for reporting @izmeez (and sorry I missed this last month!). @drupix, thanks so much for finding the problem. I found two other places with the same issue.

I pushed the fix directly to the main branch by mistake, so no merging needed. I'll do a new release in a minute.
